
--DROP TABLE ACCOUNT;
--DROP TABLE CLIENT;
--DROP TABLE ADDRESS;
--DROP TABLE QUERY;
USE [master]
GO
/****** Object:  Database [company]    Script Date: 4/30/2016 10:48:08 AM ******/
CREATE DATABASE [company]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'company', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL11.PETR\MSSQL\DATA\company.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'company_log', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL11.PETR\MSSQL\DATA\company_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [company] SET COMPATIBILITY_LEVEL = 110
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [company].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [company] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [company] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [company] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [company] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [company] SET ARITHABORT OFF 
GO
ALTER DATABASE [company] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [company] SET AUTO_CREATE_STATISTICS ON 
GO
ALTER DATABASE [company] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [company] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [company] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [company] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [company] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [company] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [company] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [company] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [company] SET  DISABLE_BROKER 
GO
ALTER DATABASE [company] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [company] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [company] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [company] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [company] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [company] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [company] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [company] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [company] SET  MULTI_USER 
GO
ALTER DATABASE [company] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [company] SET DB_CHAINING OFF 
GO
ALTER DATABASE [company] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [company] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
USE [company]
GO
/****** Object:  Table [dbo].[ACCOUNT]    Script Date: 4/30/2016 10:48:08 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ACCOUNT](
	[ACCOUNT_ID] [int] IDENTITY(1,1) NOT NULL,
	[PRODUCT_NAME] [nchar](10) NOT NULL,
	[CLIENT_ID] [int] NOT NULL,
	[BALANCE] [money] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ACCOUNT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[ADDRESS]    Script Date: 4/30/2016 10:48:08 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ADDRESS](
	[ADDRESS_ID] [int] IDENTITY(1,1) NOT NULL,
	[STREET_1] [nvarchar](50) NULL,
	[STREET_2] [nvarchar](50) NULL,
	[CITY] [nchar](30) NOT NULL,
	[PROVINCE] [nchar](20) NOT NULL,
	[COUNTRY] [nvarchar](50) NOT NULL,
	[POSTAL_CODE] [nchar](10) NULL,
PRIMARY KEY CLUSTERED 
(
	[ADDRESS_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[CLIENT]    Script Date: 4/30/2016 10:48:08 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CLIENT](
	[CLIENT_ID] [int] IDENTITY(1,1) NOT NULL,
	[FIRST_NAME] [nvarchar](50) NOT NULL,
	[LAST_NAME] [nvarchar](50) NOT NULL,
	[EMAIL] [nvarchar](50) NULL,
	[PHONE] [nvarchar](20) NULL,
	[ADDRESS_ID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[CLIENT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[QUERY]    Script Date: 4/30/2016 10:48:08 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[QUERY](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[name] [nvarchar](50) NOT NULL,
	[sql] [nvarchar](max) NOT NULL,
	[map] [nvarchar](max) NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
ALTER TABLE [dbo].[ACCOUNT]  WITH CHECK ADD  CONSTRAINT [FK_ACCOUNT_CLIENT] FOREIGN KEY([CLIENT_ID])
REFERENCES [dbo].[CLIENT] ([CLIENT_ID])
GO
ALTER TABLE [dbo].[ACCOUNT] CHECK CONSTRAINT [FK_ACCOUNT_CLIENT]
GO
ALTER TABLE [dbo].[CLIENT]  WITH CHECK ADD  CONSTRAINT [FK_CLIENT_ADDRESS] FOREIGN KEY([ADDRESS_ID])
REFERENCES [dbo].[ADDRESS] ([ADDRESS_ID])
GO
ALTER TABLE [dbo].[CLIENT] CHECK CONSTRAINT [FK_CLIENT_ADDRESS]
GO
USE [master]
GO
ALTER DATABASE [company] SET  READ_WRITE 
GO
